[package]
name = "quickwit-init"
version = "0.4.0"
edition = "2021"
license = "AGPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
promptea = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }