[package]
name = "quickwit-cli"
description = "Command line interface for launching and managing Quickwit clusters"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

default-run = "quickwit"

[[bin]]
name = "quickwit"
path = "src/main.rs"

[[bin]]
name = "generate_markdown"
path = "src/generate_markdown.rs"

[dependencies]
anyhow = { workspace = true }
backtrace = { workspace = true, optional = true }
bytesize = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
console-subscriber = { workspace = true, optional = true }
dialoguer = { workspace = true }
futures = { workspace = true }
humantime = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
numfmt = { workspace = true }
once_cell = { workspace = true }
openssl-probe = { workspace = true, optional = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde_json = { workspace = true }
tabled = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
thousands = { workspace = true }
tikv-jemalloc-ctl = { workspace = true, optional = true }
tikv-jemallocator = { workspace = true, optional = true }
time = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }

quickwit-actors = { workspace = true }
quickwit-cluster = { workspace = true }
quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-doc-mapper = { workspace = true }
quickwit-index-management = { workspace = true }
quickwit-indexing = { workspace = true }
quickwit-ingest = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-rest-client = { workspace = true }
quickwit-search = { workspace = true }
quickwit-serve = { workspace = true }
quickwit-storage = { workspace = true }
quickwit-telemetry = { workspace = true }

[dev-dependencies]
predicates = { workspace = true }
reqwest = { workspace = true }

quickwit-actors = { workspace = true, features = ["testsuite"] }
quickwit-common = { workspace = true, features = ["testsuite"] }
quickwit-config = { workspace = true, features = ["testsuite"] }
quickwit-metastore = { workspace = true, features = ["testsuite"] }
quickwit-storage = { workspace = true, features = ["testsuite"] }

[features]
jemalloc = ["dep:tikv-jemalloc-ctl", "dep:tikv-jemallocator"]
jemalloc-profiled = [
  "dep:backtrace",
  "quickwit-common/jemalloc-profiled",
  "quickwit-serve/jemalloc-profiled"
]
ci-test = []
pprof = ["quickwit-serve/pprof"]
openssl-support = ["openssl-probe"]
# Requires to enable tokio unstable via RUSTFLAGS="--cfg tokio_unstable"
tokio-console = ["console-subscriber", "quickwit-common/named_tasks"]
release-feature-set = [
  "jemalloc",
  "openssl-support",
  "pprof",
  "quickwit-indexing/kafka",
  "quickwit-indexing/kinesis",
  "quickwit-indexing/pulsar",
  "quickwit-indexing/sqs",
  "quickwit-indexing/vrl",
  "quickwit-storage/azure",
  "quickwit-storage/gcs",
  "quickwit-metastore/postgres",
  "quickwit-doc-mapper/multilang",
]
release-feature-vendored-set = [
  "jemalloc",
  "openssl-support",
  "pprof",
  "quickwit-indexing/kinesis",
  "quickwit-indexing/pulsar",
  "quickwit-indexing/sqs",
  "quickwit-indexing/vrl",
  "quickwit-indexing/vendored-kafka",
  "quickwit-storage/azure",
  "quickwit-storage/gcs",
  "quickwit-metastore/postgres",
  "quickwit-doc-mapper/multilang",
]
release-macos-feature-vendored-set = [
  "jemalloc",
  "openssl-support",
  "quickwit-indexing/kinesis",
  "quickwit-indexing/pulsar",
  "quickwit-indexing/sqs",
  "quickwit-indexing/vrl",
  "quickwit-indexing/vendored-kafka-macos",
  "quickwit-storage/azure",
  "quickwit-storage/gcs",
  "quickwit-metastore/postgres",
  "quickwit-doc-mapper/multilang",
]
release-jemalloc-profiled = [
  "release-feature-set",
  "jemalloc-profiled",
]

[package.metadata.cargo-machete]
# used to enable the `multilang` feature
ignored = ["quickwit-doc-mapper"]
