[package]
name = "quickwit-core"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Core crate of quickwit"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
byte-unit = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
tantivy = { workspace = true, features = ["mmap", "lz4-compression", "zstd-compression", "quickwit"] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

quickwit-actors = { workspace = true }
quickwit-common = { workspace = true, features = ["metrics", "system"] }
quickwit-config = { workspace = true }
quickwit-directories = { workspace = true, features = ["storage", "tokio-time"] }
quickwit-doc-mapper = { workspace = true }
quickwit-indexing = { workspace = true }
quickwit-janitor = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-storage = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
serde_yaml = { workspace = true }
