[workspace]

members = [
  "quickwit-cli",
  "quickwit-cluster",
  "quickwit-core",
  "quickwit-doc-mapping",
  "quickwit-directories",
  "quickwit-metastore",
  "quickwit-proto",
  "quickwit-search",
  "quickwit-serve",
  "quickwit-storage",
]
