[target.x86_64-unknown-linux-gnu]
image = "quickwitinc/builder-x86_64-unknown-linux-gnu:latest"

[target.x86_64-unknown-linux-musl]
image = "quickwitinc/builder-x86_64-unknown-linux-musl:latest"
RUSTFLAGS="LIB_LDFLAGS=-L/usr/lib/x86_64-linux-gnu CFLAGS=-I/usr/local/musl/include CC=musl-gcc"

[target.aarch64-unknown-linux-gnu]
image = "quickwitinc/builder-aarch64-unknown-linux-gnu:latest"

# TODO: https://github.com/quickwit-inc/quickwit/issues/715
# [target.aarch64-unknown-linux-musl]
# image = "quickwitinc/builder-aarch64-unknown-linux-musl:latest"
# RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc"

# [target.armv7-unknown-linux-gnueabihf]
# image = "quickwitinc/armv7-unknown-linux-gnueabihf:latest"

# [target.armv7-unknown-linux-musleabihf]
# image = "quickwitinc/armv7-unknown-linux-musleabihf:latest"
