#
# Index config file for hdfs-logs dataset with a retention policy configured.
#

version: 0.4

index_id: hdfs-logs-retention-policy

doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
      input_formats:
        - unix_timestamp
      output_format: unix_timestamp_secs
      precision: seconds
      fast: true
    - name: tenant_id
      type: u64
    - name: severity_text
      type: text
      tokenizer: raw
    - name: body
      type: text
      tokenizer: default
      record: position
    - name: resource
      type: json
      tokenizer: raw
  tag_fields: [tenant_id]
  timestamp_field: timestamp

search_settings:
  default_search_fields: [severity_text, body]

retention:
  period: 90 days
  schedule: daily

indexing_settings:
  commit_timeout_secs: 10
  split_num_docs_target: 10000000
