[package]
name = "quickwit-telemetry"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's telemetry"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
async-trait = { workspace = true }
hostname = { workspace = true }
md5 = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
username = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }

# This is actually not used directly the goal is to fix the version
# used by reqwest. 0.8.30 has an unclear license.
encoding_rs = { workspace = true }
