[package]
name = "quickwit-metastore"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
bytesize = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true, optional = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
regex-syntax = { workspace = true }
sea-query = { workspace = true, optional = true }
sea-query-binder = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sqlx = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
ulid = { workspace = true, features = ["serde"] }
uuid = { workspace = true }
utoipa = { workspace = true }

quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-doc-mapper = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-query = { workspace = true }
quickwit-storage = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
futures = { workspace = true }
hyper-util = { workspace = true }
md5 = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

quickwit-common = { workspace = true, features = ["testsuite"] }
quickwit-config = { workspace = true, features = ["testsuite"] }
quickwit-doc-mapper = { workspace = true, features = ["testsuite"] }
quickwit-proto = { workspace = true, features = ["testsuite"] }
quickwit-storage = { workspace = true, features = ["testsuite"] }

[features]
ci-test = []
postgres = ["quickwit-proto/postgres", "sea-query", "sea-query-binder", "sqlx"]
testsuite = ["mockall", "tempfile", "quickwit-config/testsuite"]
