[package]
name = "quickwit-common"
version = "0.4.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Util crate of quickwit"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-speed-limit = { workspace = true }
async-trait = { workspace = true }
byte-unit = { workspace = true }
colored = { workspace = true }
dyn-clone = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
home = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
pin-project-lite = { workspace = true }
pnet = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
warp = { workspace = true }
utoipa = { workspace = true }

[features]
testsuite = []

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
