[package]
name = 'quickwit-storage'
version = '0.1.0'
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = '2018'
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io

[dependencies]
async-trait = '0.1'
md5 = '0.7'
anyhow = '1'
futures = '0.3'
bytes = '1'
base64 = '0.13'
tracing = '0.1'
once_cell = '1'
regex = '1'
thiserror = '1'
rand = '0.8'

[dependencies.rusoto_core]
version = '0.46'
default-features = false
features = ['rustls']

[dependencies.rusoto_s3]
version = '0.46'
default-features = false
features = ['rustls']

[dependencies.tokio]
version = '1'
features = ['full']

[dependencies.tokio-util]
version = '0.6'
features = ['full']

[dependencies.mockall]
version = "0.9"
optional = true

[dependencies.tempfile]
version = "3"
optional = true

[dev-dependencies]
tracing-subscriber = '0.2'
tempfile = '3'
mockall = '0.9'

[features]
testsuite = ["mockall", "tempfile"]
ci-test = []
