#
# Index config file for gh-archive dataset.
#
version: 0

index_id: gh-archive

doc_mapping:
  field_mappings:
    - name: id
      type: text
      tokenizer: raw
    - name: type
      type: text
      fast: true
      tokenizer: raw
    - name: public
      type: bool
      fast: true
    - name: payload
      type: json
      tokenizer: default
    - name: org
      type: json
      tokenizer: default
    - name: repo
      type: json
      tokenizer: default
    - name: actor
      type: json
      tokenizer: default
    - name: other
      type: json
      tokenizer: default
    - name: created_at
      type: datetime
      input_formats:
        - "rfc3339"
      precision: "seconds"
      fast: true

indexing_settings:
  timestamp_field: created_at

search_settings:
  default_search_fields: []
