[package]
name = "quickwit-serve"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's search service"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
mime_guess = { workspace = true }
once_cell = { workspace = true }
prometheus = { workspace = true }
regex = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
termcolor = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
warp = { workspace = true }

quickwit-actors = { workspace = true }
quickwit-cluster = { workspace = true }
quickwit-common = { workspace = true, features = ["metrics", "system"] }
quickwit-config = { workspace = true }
quickwit-core = { workspace = true }
quickwit-directories = { workspace = true, features = ["storage", "tokio-time"] }
quickwit-doc-mapper = { workspace = true }
quickwit-indexing = { workspace = true }
quickwit-ingest-api = { workspace = true }
quickwit-janitor = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-opentelemetry = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-search = { workspace = true }
quickwit-storage = { workspace = true }

[dev-dependencies]
assert-json-diff = { workspace = true }
chitchat = { workspace = true }
itertools = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }

quickwit-cluster = { workspace = true, features = ["testsuite"] }
quickwit-common = { workspace = true, features = ["metrics", "system", "testsuite"] }
quickwit-indexing = { workspace = true, features = ["testsuite"] }
quickwit-metastore = { workspace = true, features = ["testsuite"] }
quickwit-search = { workspace = true, features = ["testsuite"] }
quickwit-storage = { workspace = true, features = ["testsuite"] }
