[package]
name = 'quickwit-indexing'
version = '0.1.0'
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = '2018'
license = 'AGPL-3.0-or-later'  # For a commercial, license, contact hello@quickwit.io
description = "Quickwit indexing"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = "1"
async-trait = "0.1"
backoff = { version = "0.3", features = ["tokio"] }
byte-unit = "4"
fail = "0.4"
flume = "0.10"
futures = "0.3"
itertools = "0.10"
once_cell = "1"
quickwit-actors = {path = "../quickwit-actors" }
quickwit-common = {path = "../quickwit-common" }
quickwit-directories = {path = "../quickwit-directories"}
quickwit-index-config = {path = "../quickwit-index-config", features=["testsuite"]}
quickwit-metastore = {path = "../quickwit-metastore" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
rdkafka = { version = "0.26", features = ["cmake-build", "ssl"], optional = true }
serde = "1"
serde_json = "1"
tantivy = { git= "https://github.com/quickwit-inc/tantivy", rev="a622e2f"}
tempfile = "3.2"
thiserror = "1"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
ulid = "0.4"
tokio-stream = "0.1.6"
warp = '0.3'
hyper = { version = "0.14", features = ["stream", "server", "http1", "http2", "tcp", "client"] }
prometheus = "0.13"

[features]
kafka = ["rdkafka"]
kafka-broker-external-service = []

[dev-dependencies]
mockall = "0.9"
proptest = "1"
quickwit-common = {path="../quickwit-common", version="0.1"}
quickwit-metastore = {path = "../quickwit-metastore", features=["testsuite"]}
quickwit-storage = {path = "../quickwit-storage", features=["testsuite"]}
rand = '0.8'

[[test]]
name = "failpoints"
path = "failpoints/mod.rs"
required-features = ["fail/failpoints"]
