[package]
name = "quickwit-lambda-client"
description = "AWS Lambda client for Quickwit leaf search invocation and deployment"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
aws-config = { workspace = true }
aws-sdk-lambda = { workspace = true }
base64 = { workspace = true }
prost = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

quickwit-config = { workspace = true }
quickwit-lambda-server = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-search = { workspace = true }

[build-dependencies]
ureq = { workspace = true }

[features]
default = []
testsuite = []
