[package]
name = "quickwit-metastore"
version = "0.1.0"
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = "2021"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's metastore"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
chrono = "0.4"
diesel = { version = "1.4", features = ["postgres", "chrono", "extras"], optional = true }
diesel_migrations =  { version = "1.4", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.6", features = ["full"]}
tracing = "0.1"
openssl = { version = "*", optional = true }
openssl-probe = { version="0.1.2", optional = true }

quickwit-index-config = { version = "0.1.0", path = "../quickwit-index-config" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }

[dependencies.mockall]
version = "0.9"
optional = true

[dependencies.tempfile]
version = "3"
optional = true

[dev-dependencies]
dotenv = "0.15"
mockall = '0.9'
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage", features=["testsuite"]}
quickwit-index-config = { version = "0.1.0", path = "../quickwit-index-config", features=["testsuite"] }
tempfile = '3'

[features]
testsuite = ["mockall", "tempfile"]
ci-test = []
postgres = [ "diesel", "diesel_migrations", "openssl", "openssl-probe"]
