#
# Index config file for wikipedia dataset.
#

version: 0.5

index_id: wikipedia

doc_mapping:
  field_mappings:
    - name: title
      type: text
      tokenizer: default
      record: position
      stored: true
      fieldnorms: true
    - name: body
      type: text
      tokenizer: default
      record: position
      stored: true
      fieldnorms: true
    - name: url
      type: text
      tokenizer: raw

search_settings:
  default_search_fields: [title, body]

indexing_settings:
  commit_timeout_secs: 10
