[package]
name = 'quickwit-proto'
version = "0.2.0"
authors = ['Quickwit, inc <hello@quickwit.io>']
edition = '2021'
license = 'AGPL-3.0-or-later'  # For a commercial, license, contact hello@quickwit.io
description = "Quickwit's protos"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
tonic = "0.6"
prost = { version = "0.9", default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.6"
prost-build = "0.9"
