[package]
name = "quickwit-aws"
version = "0.6.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Utilities for working with AWS."
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
aws-smithy-client = { workspace = true }
aws-smithy-async = { workspace = true }
aws-sdk-kinesis = { workspace = true, optional = true }
aws-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
hyper = { workspace = true }
hyper-rustls = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tower = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
quickwit-actors = { workspace = true, features = ["testsuite"] }

[features]
kinesis = ["aws-sdk-kinesis"]
