[package]
name = "quickwit-aws"
version = "0.3.1"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Utilities for working with AWS."
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
ec2_instance_metadata = { workspace = true }
futures = { workspace = true }
hyper-rustls = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rusoto_core = { workspace = true }
rusoto_kinesis = { workspace = true, optional = true }
rusoto_s3 = { workspace = true }
rusoto_sts = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[features]
kinesis = ["rusoto_kinesis"]
