[package]
name = 'quickwit-directories'
version = '0.1.0'
authors = ['Quickwit, Inc. <hello@quickwit.io>']
edition = '2018'
license = 'AGPL-3.0-or-later'  # For a commercial, license, contact hello@quickwit.io

[dependencies]
attohttpc = { version = "0.16", default-features = false, features = ["json"] }
crossbeam = "0.8"
futures = "0.3"
iobuffer = "0.2"
rusoto_s3 = { version = "0.46", default-features = false, features = [
  "rustls"
] }
rusoto_core = { version = "0.46", default-features = false, features = [
  "rustls"
] }
serde = "1"
serde_cbor = "0.11"
serde_json = "1"
structopt = "0.3"
tantivy = { git= "https://github.com/quickwit-inc/tantivy", rev="8a4df0586", default-features=false, features = ["mmap", "lz4-compression"] }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
uuid = "0.8"
once_cell = "1"
lru = "0.6"
tokio = { version = "1", features = ["sync"] }
tracing = "0.1"
tracing-subscriber = "0.2"
thiserror = "1"
flume = "0.10"
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"

[dev-dependencies]
tracing-subscriber = '0.2'
