# ============================ Quickwit Configuration ==============================
#
# Website: https://quickwit.io
# Docs: https://quickwit.io/docs/
#
# -------------------------------- General settings --------------------------------
#
# Config file version.
#
version: 0
#
# Node ID must be unique in your cluster. If not set, a random ID is given at each boot.
#
#node_id: node-1
#
# Path to directory where data is persisted. Default to `./qwdata`.
#
#data_dir_path: /path/to/data
#
# Metastore URI. Default to `{data_dir_path}/indexes` which is a file backed metastore
# and mostly convenient for testing. A cluster would require a metastore backed by S3 or
# postgreqsl.
#
#metastore_uri: s3://your-bucket/indexes
#metastore_uri: postgres://username:password@host:port/db
#
# Default index root URI which define the location where index data (splits) is stored
# following the scheme `{default_index_root_uri}/{index-id}`. Default to `data_dir/indexes`.
#
#default_index_root_uri: s3://your-bucket/indexes
#
#
#
# -------------------------------- Indexer settings --------------------------------
#
# By default an indexer is only accessible on localhost on http port 7280.
#
#indexer:
#  rest_listen_address: 127.0.0.1
#  rest_listen_port: 7280
#  split_store_max_num_bytes: 200G
#  split_store_max_num_splits: 10000
#
# -------------------------------- Searcher settings --------------------------------
#
# By default a searcher is only accessible on localhost on http port 7280.
#
#searcher:
#  rest_listen_address: 127.0.0.1
#  rest_listen_port: 7280
#  peer_seeds:
#    - quickwit-searcher-0.local
#    - quickwit-searcher-1.local
#  fast_field_cache_capacity: 10G
#  split_footer_cache_capacity: 1G
#

