[package]
name = "quickwit-query"
description = "Query DSL definition and parsing"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
bitpacking = { workspace = true }
hex = { workspace = true }
lindera-core = { workspace = true, optional = true }
lindera-dictionary = { workspace = true, optional = true }
lindera-tokenizer = { workspace = true, optional = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tantivy = { workspace = true }
tantivy-fst = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
rustc-hash = { workspace = true }
whichlang = { workspace = true, optional = true }

quickwit-common = { workspace = true }
quickwit-datetime = { workspace = true }
quickwit-proto = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
proptest = { workspace = true }
time = { workspace = true }

quickwit-common = { workspace = true, features = ["testsuite"] }

[features]
multilang = [
    "lindera-core",
    "lindera-dictionary",
    "lindera-tokenizer",
    "whichlang",
]

[[bench]]
name = "tokenizers_bench"
harness = false

[[bench]]
name = "multilang_tokenizers_bench"
harness = false
