[package]
name = "quickwit-cli"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2018"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit is a cost-efficient search engine."
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[[bin]]
name = "quickwit"
path = "src/main.rs"

[dependencies]
anyhow = "1"
byte-unit = "4"
clap = { version = "2", features = ["yaml"] }
futures = "0.3"
quickwit-actors = { version = "0.1.0", path = "../quickwit-actors" }
quickwit-core = { version = "0.1.0", path = "../quickwit-core" }
quickwit-common = { version = "0.1.0", path = "../quickwit-common" }
quickwit-metastore = { version = "0.1.0", path = "../quickwit-metastore" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
quickwit-indexing = {path = "../quickwit-indexing" }
quickwit-index-config = { version = "0.1.0", path = "../quickwit-index-config" }
quickwit-search = { version = "0.1", path = "../quickwit-search" }
quickwit-serve = { version = "0.1", path = "../quickwit-serve" }
quickwit-telemetry = { version = "0.1", path = "../quickwit-telemetry" }
quickwit-proto = { version = "0.1", path = "../quickwit-proto" }
tracing = '0.1'
tracing-subscriber = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["full"] }
crossterm = "0.20"
atty = "0.2"
once_cell = "1"
serde_json = "1.0"
tempfile = "3"
json_comments = "0.2"
chrono = "0.4"

[dev-dependencies]
assert_cmd = "1"
predicates = "2"
reqwest = { version = "0.11", default-features=false, features = ["json", "rustls-tls"] }
serial_test = "0.5.1"

[features]
ci-test = []
