[package]
name = "quickwit-cli"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2018"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io

[dependencies]
anyhow = "1"
byte-unit = "4"
clap = { version = "2", features = ["yaml"] }
quickwit-core = { version = "0.1.0", path = "../quickwit-core" }
quickwit-metastore = { version = "0.1.0", path = "../quickwit-metastore" }
quickwit-storage = { version = "0.1.0", path = "../quickwit-storage" }
quickwit-doc-mapping = { version = "0.1.0", path = "../quickwit-doc-mapping" }
quickwit-search = { version = "0.1", path = "../quickwit-search" }
quickwit-proto = { version = "0.1", path = "../quickwit-proto" }
tracing = '0.1'
tracing-subscriber = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["full"] }
crossterm = "0.19.0"
atty = "0.2"
regex = "1"
once_cell = "1"
serde_json = "1.0"
tempfile = "3"
