[package]
name = "quickwit-doc-mapper"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later" # For a commercial, license, contact hello@quickwit.io
description = "Quickwit index configuration"
repository = "https://github.com/quickwit-inc/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = "1"
base64 = "0.13"
chrono = "0.4"
dyn-clone = "1.0.4"
itertools = '0.10'
once_cell = "1.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tantivy = { git = "https://github.com/quickwit-inc/tantivy", rev = "48c47f0d3", default-features = false, features = ["mmap", "lz4-compression"] }
tantivy-query-grammar = { git = "https://github.com/quickwit-inc/tantivy/", rev = "48c47f0d3" }
thiserror = "1.0"
tracing = "0.1.29"
typetag = "0.1"

[dependencies.quickwit-proto]
path = '../quickwit-proto'

[dependencies.mockall]
version = "0.11"
optional = true

[dev-dependencies]
mockall = "0.11"

[dev-dependencies.matches]
version = "0.1.8"

[features]
testsuite = ["mockall"]

