[package]
name = "quickwit-lambda"
description = "Serverless Quickwit on AWS Lambda"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "indexer"
path = "src/bin/indexer.rs"

[[bin]]
name = "searcher"
path = "src/bin/searcher.rs"

[features]
s3-localstack-tests = []

[dependencies]
anyhow = { workspace = true }
aws_lambda_events = "0.16.0"
bytesize = { workspace = true }
chitchat = { workspace = true }
chrono = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
lambda_http = "0.8.0"
lambda_runtime = "0.13.0"
mime_guess =  { workspace = true }
once_cell = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true, features = [
    "reqwest-client",
    "reqwest-rustls",
    "http-proto",
] }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
warp = {  workspace = true , features = ["compression-gzip"] }


quickwit-actors = { workspace = true }
quickwit-cli = { workspace = true }
quickwit-cluster = { workspace = true }
quickwit-common = { workspace = true }
quickwit-config = { workspace = true }
quickwit-index-management = { workspace = true }
quickwit-indexing = { workspace = true }
quickwit-ingest = { workspace = true }
quickwit-janitor = { workspace = true }
quickwit-metastore = { workspace = true }
quickwit-proto = { workspace = true }
quickwit-search = { workspace = true }
quickwit-serve = { workspace = true }
quickwit-storage = { workspace = true }
quickwit-telemetry = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
