[index.create]
long_about = """
Creates an index of ID `index` at `index-uri` configured by a [YAML config file](index-config.md) located at `index-config`.
The index config lets you define the mapping of your document on the index and how each field is stored and indexed.
If `index-uri` is omitted, `index-uri` will be set to `{default_index_root_uri}/{index}`, more info on [Quickwit config docs](config.md).
The command fails if an index already exists unless `overwrite` is passed. 
When `overwrite` is enabled, the command deletes all the files stored at `index-uri` before creating a new index. 
"""

[[index.create.examples]]
name= "Create a new index."
command = '''
curl -o wikipedia_index_config.yaml https://raw.githubusercontent.com/quickwit-inc/quickwit/main/config/tutorials/wikipedia/index-config.yaml
quickwit index create --index-config wikipedia_index_config.yaml  --config=./config/quickwit.yaml
'''

[index.ingest]
long_about = """
Indexes a dataset consisting of newline-delimited JSON objects located at `input-path` or read from *stdin*. 
The data is appended to the target index of ID `index` unless `overwrite` is passed. `input-path` can be a file or another command output piped into stdin. 
Currently, only local datasets are supported.
By default, Quickwit's indexer will work with a heap of 2 GiB of memory. Learn how to change `heap-size` in the [index config doc page](index-config.md).
"""

[[index.ingest.examples]]
name = "Indexing a dataset from a file"
command = '''
curl -o wiki-articles-10000.json https://quickwit-datasets-public.s3.amazonaws.com/wiki-articles-10000.json
quickwit index ingest --index wikipedia --config=./config/quickwit.yaml --input-path wiki-articles-10000.json
'''

[[index.ingest.examples]]
name = "Indexing a dataset from stdin"
command = "cat hdfs-log.json | quickwit index ingest --index wikipedia --config=./config/quickwit.yaml"

[index.gc]
note = """
Intermediate files are created while executing Quickwit commands. 
These intermediate files are always cleaned at the end of each successfully executed command. 
However, failed or interrupted commands can leave behind intermediate files that need to be removed. 
Also, note that using a very short grace period (like seconds) can cause the removal of intermediate files being operated on, especially when using Quickwit concurrently on the same index. 
In practice, you can settle with the default value (1 hour) and only specify a lower value if you really know what you are doing.
"""

[index.search]
long_about = """
Searches an index with ID `--index` and returns the documents matching the query specified with `--query`.
More details on the [query language page](query-language.md).
The offset of the first hit returned and the number of hits returned can be set with the `start-offset` and `max-hits` options. 
It's possible to override the default search fields `search-fields` option to define the list of fields that Quickwit will search into if the user query does not explicitly target a field in the query.
Search can also be limited to a time range using the `start-timestamp` and `end-timestamp` options. 
These timestamp options are useful for boosting query performance when using a time series dataset.
"""

[[index.search.examples]]
name = "Searching a index"
command = '''
quickwit index search --index wikipedia --query "Barack Obama" --config ./config/quickwit.yaml
# If you have jq installed.
quickwit index search --index wikipedia --query "Barack Obama" --config ./config/quickwit.yaml | jq '.hits[].title'
'''

[[index.search.examples]]
name = "Limiting the result set to 50 hits"
command = '''
quickwit index search --index wikipedia --query "Barack Obama" --max-hits 50 --config ./config/quickwit.yaml
# If you have jq installed.
quickwit index search --index wikipedia --query "Barack Obama" --max-hits 50 --config ./config/quickwit.yaml | jq '.numHits'
'''

[[index.search.examples]]
name = "Looking for matches in the title only"
command = '''
quickwit index search --index wikipedia --query "search" --search-fields title --config ./config/quickwit.yaml
# If you have jq installed.
quickwit index search --index wikipedia --query "search" --search-fields title --config ./config/quickwit.yaml | jq '.hits[].title'
'''

[[index.describe.examples]]
name = "Displays descriptive statistics of your index"
command = '''quickwit index describe --index wikipedia --config ./config/quickwit.yaml

1. General infos
===============================================================================
Index id:                           wikipedia
Index uri:                          file:///home/quickwit-indices/qwdata/indexes/wikipedia
Number of published splits:         1
Number of published documents:      300000
Size of published splits:           448 MB

2. Statistics on splits
===============================================================================
Document count stats:
Mean ± σ in [min … max]:            300000 ± 0 in [300000 … 300000]
Quantiles [1%, 25%, 50%, 75%, 99%]: [300000, 300000, 300000, 300000, 300000]

Size in MB stats:
Mean ± σ in [min … max]:            448 ± 0 in [448 … 448]
Quantiles [1%, 25%, 50%, 75%, 99%]: [448, 448, 448, 448, 448]
'''

[[index.delete.examples]]
name = "Delete your index"
command = '''quickwit index delete --index wikipedia --config ./config/quickwit.yaml'''


[service.run.searcher]
long_about = """
Starts a web server at `rest_listing_address:rest_list_port` that exposes the [Quickwit REST API](search-api.md)
where `rest_listing_address` and `rest_list_port` are defined in Quickwit config file (quickwit.yaml).
The node can optionally join a cluster using the `peer_seeds` parameter. 
This list of node addresses is used to discover the remaining peer nodes in the cluster through a gossip protocol (SWIM).
"""

note = """
Behind the scenes, Quickwit needs to open the following port for cluster formation and workload distribution:

    TCP port (default is 7280) for REST API
    TCP and UDP port (default is 7280) for cluster membership protocol
    TCP port + 1 (default is 7281) for gRPC address for the distributed search

If ports are already taken, the serve command will fail.
"""

[[service.run.searcher.examples]]
name = "Start a Searcher"
command = "quickwit service run searcher --config=./config/quickwit.yaml"

[[service.run.searcher.examples]]
name = "Make a search request on a wikipedia index"
command = '''
# To create wikipedia index and ingest data, go to our tutorial https://quickwit.io/docs/get-started/quickstart.
# Start a searcher.
quickwit service run searcher --config=./config/quickwit.yaml
# Make a request.
curl "http://127.0.0.1:7280/api/v1/wikipedia/search?query=barack+obama" 
'''


[[service.run.searcher.examples]]
name = "Make a search stream request on a Github archive index"
command = '''
# Create gh-archive index.
curl -o gh_archive_index_config.yaml https://raw.githubusercontent.com/quickwit-inc/quickwit/main/config/tutorials/gh-archive/index-config.yaml
quickwit index create --index-config gh_archive_index_config.yaml --config ./config/quickwit.yaml
# Download a data sample and ingest it.
curl https://quickwit-datasets-public.s3.amazonaws.com/gh-archive-2022-01-text-only-10000.json.gz | gunzip | cargo r index ingest --index gh-archive --config=./config/quickwit.yaml
# Start server.
quickwit service run searcher --config=./config/quickwit.yaml
# Finally make the search stream request.
curl "http://127.0.0.1:7280/api/v1/gh-archive/search/stream?query=log4j&fastField=id&outputFormat=csv"
# Make a search stream request with HTTP2.
curl --http2-prior-knowledge "http://127.0.0.1:7280/api/v1/gh-archive/search/stream?query=log4j&fastField=id&outputFormat=csv"
'''

[service.run.indexer]
long_about = """
Starts an indexing server that consumes the sources of index IDs passed in `--indexes` argument.
"""

[[service.run.indexer.examples]]
name = "Add a source to an index and start an Indexer"
command = '''
quickwit source add --index wikipedia --source wikipedia-source --type file --params '{"filepath":"wiki-articles-10000.json"}'
quickwit service run indexer --indexes wikipedia --config=./config/quickwit.yaml
'''


[[source.add.examples]]
name = "Add a file source to `wikipedia` index"
command = '''
quickwit source add --index wikipedia --source wikipedia-source --type file --params '{"filepath":"wiki-articles-10000.json"}' --config ./config/quickwit.yaml
'''

[[source.add.examples]]
name = "Add a Kafka source to `wikipedia` index"
command = '''
cat << EOF > wikipedia-kafka-source.json
{
  "topic": "wikipedia",
  "client_params": {
    "bootstrap.servers": "localhost:9092",
    "group.id": "my-group-id",
    "security.protocol": "SSL"
  }
}
EOF
quickwit source add --index wikipedia --source wikipedia-source --type kafka --params wikipedia-kafka-source.json --config ./config/quickwit.yaml
'''

[[source.describe.examples]]
name = "Describe a `wikipedia-source` source"
command = '''
quickwit source describe --index wikipedia --source wikipedia-source --config ./config/quickwit.yaml
'''

[[source.list.examples]]
name = "List `wikipedia` index sources"
command = '''
quickwit source list --index wikipedia --config ./config/quickwit.yaml
'''


[[source.delete.examples]]
name = "Delete a `wikipedia-source` source"
command = '''
quickwit source delete --index wikipedia --source wikipedia-source --config ./config/quickwit.yaml
'''
