[package]
name = "quickwit-codegen"
version = "0.6.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2021"
license = "AGPL-3.0-or-later"                           # For a commercial, license, contact hello@quickwit.io
description = "Generate traits, adapters, and gRPC clients/servers from proto files"
repository = "https://github.com/quickwit-oss/quickwit"
homepage = "https://quickwit.io/"
documentation = "https://quickwit.io/docs/"

[dependencies]
anyhow = { workspace = true }
heck = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
prost = { workspace = true }
prost-build = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
tonic-build = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
