[package]
name = "quickwit-codegen"
description = "Generate traits, adapters, and gRPC clients/servers from proto files."

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
heck = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
prost-build = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
tonic-build = { workspace = true }
tonic-prost-build = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
serde = { workspace = true }
